apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-native-demo-service
spec:
  params:
    - default: 'https://github.com/wpernath/quarkus-demo-service'
      description: URL of the source code to build
      name: git-url
      type: string
    - default: wpernath
      description: 'user of the target repository '
      name: repo-user
      type: string
    - description: Password of the target repository
      name: repo-pwd
      type: string
    - default: qd1
      description: ns to deploy this app to
      name: namespace
      type: string
  tasks:
    - name: package
      params:
        - name: GOALS
          value:
            - '-DskipTests'
            - clean
            - package
        - name: CONTEXT_DIR
          value: the-source/
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: maven-caching
      workspaces:
        - name: source
          workspace: the-sources
        - name: maven-settings
          workspace: maven-settings
    - name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: quarkus-3.2
        - name: refspec
          value: ''
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: subdirectory
          value: the-source
        - name: sparseCheckoutDirectories
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: httpProxy
          value: ''
        - name: httpsProxy
          value: ''
        - name: noProxy
          value: ''
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:429ba9c10dfcff4ee0154ab75f9bd06fd306f019c0ed0b062ba7c03e56e3e33b
        - name: userHome
          value: /home/git
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: the-sources
    - name: deploy
      params:
        - name: SCRIPT
          value: >-
            oc apply -f ./the-source/target/kubernetes/kubernetes.yml -n
            $(params.namespace)
        - name: VERSION
          value: latest
      runAfter:
        - build-push-native-image
        #- package
      taskRef:
        kind: ClusterTask
        name: openshift-client
      workspaces:
        - name: manifest-dir
          workspace: the-sources
    - name: build-push-native-image
      params:
        - name: GOALS
          value:
            - package
            - '-Dnative'
            - '-Dquarkus.container-image.push=true'
            - '-Dquarkus.native.container-build=false'
            - '-Dquarkus.container-image.username=$(params.repo-user)'
            - '-Dquarkus.container-image.password=$(params.repo-pwd)'
        - name: CONTEXT_DIR
          value: the-source/
      runAfter:
        - package
      taskRef:
        kind: Task
        name: maven-caching
      workspaces:
        - name: source
          workspace: the-sources
        - name: maven-settings
          workspace: maven-settings
  workspaces:
    - name: the-sources
    - name: maven-settings
