kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: demo-service
  labels:
    app: demo-service
    app.kubernetes.io/component: demo-service
    app.kubernetes.io/instance: demo-service
    app.kubernetes.io/name: demo-service
    app.kubernetes.io/part-of: demo-service-app
spec:
  to:
    kind: Service
    name: demo-service
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
---
kind: PostgresCluster
apiVersion: postgres-operator.crunchydata.com/v1beta1
metadata:
  name: demo
spec:
  backups:
    pgbackrest:
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
  instances:
    - dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      replicas: 1
  postgresVersion: 15
  # make sure that the cat user has access to the public schema
  users:
    - name: demo
      databases:
        - demo
      options: 'SUPERUSER'

---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-kafka
spec:
  kafka:
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: '3.6'
    storage:
      type: ephemeral
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    version: 3.6.0
    replicas: 1
  entityOperator:
    topicOperator: {}
    userOperator: {}
  zookeeper:
    storage:
      type: ephemeral
    replicas: 1
---
kind: KafkaTopic
apiVersion: kafka.strimzi.io/v1beta2
metadata:
  name: kafka
  labels:
    strimzi.io/cluster: my-kafka
spec:
  partitions: 4
  replicas: 1
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
