kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: demo-service
  labels:
    app: demo-service
    app.kubernetes.io/component: demo-service
    app.kubernetes.io/instance: demo-service
    app.kubernetes.io/name: demo-service
    app.kubernetes.io/part-of: demo-service-app
spec:
  to:
    kind: Service
    name: demo-service
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
---
kind: PostgresCluster
apiVersion: postgres-operator.crunchydata.com/v1beta1
metadata:
  name: demo
spec:
  backups:
    pgbackrest:
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
  instances:
    - dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      replicas: 1
  postgresVersion: 15
    # make sure that the cat user has access to the public schema
  users:
    - name: demo
      databases:
        - demo
      options: 'SUPERUSER'

